version: '3'
services:

  routing-webapp:
    container_name: routing-webapp
    build:
      context: .
      dockerfile: ./Dockerfile_webapp.run
    ports:
      - 3000:3000
    # command: >
      #tail -f /dev/null
      # npm start

  msp1-server:
    container_name: msp1-server
    build:
      context: .
      dockerfile: ./Dockerfile.run
    ports:
      - 8000:8000
    command: >
      node MSP_server.js
        --ip ${ip_address}
        --port 8000
        --name MSP1
        --agentUrl http://${ip_address}:7080
        --schemaName MSP1-Ticket
    depends_on:
      - msp1-agent
  
  msp1-tails-server:
    container_name: msp1-tails-server
    build:
      context: ./indy-tails-server
      dockerfile: ./docker/Dockerfile.tails-server 
    ports:
      - 6543:6543
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --log-level debug
        --storage-path /home/indy/tails
    # volumes:
    #  - ${dir_name}/.indy_tails:/home/indy/tails


  msp1-agent:
    container_name: msp1-agent
    build:
      context: ./aries-cloudagent-python
      dockerfile: ./docker/Dockerfile.run
    ports:
      - 7000:7000
      - 7080:7080
    # healthcheck:
      # test: [ "CMD", "curl", "-f", "http://${ip_address}:7080" ]
      # interval: 4s
      # timeout: 4s
      # retries: 10
      # start_period: 5s
    entrypoint: aca-py
    command: >
      start
        --auto-provision
        --tails-server-base-url http://${ip_address}:6543 
        --webhook-url http://${ip_address}:8000
        --auto-respond-credential-proposal 
        --auto-respond-credential-offer 
        --auto-respond-credential-request
        --auto-verify-presentation 
        --inbound-transport http 0.0.0.0 7000 
        --inbound-transport ws 0.0.0.0 7001 
        --outbound-transport ws 
        --outbound-transport http
        --genesis-url http://${ip_address}:9000/genesis
        --log-level info
        --seed 000000000000000000000000Steward1
        --wallet-type indy 
        --wallet-key StewardWallet3 
        --wallet-name StewardWallet3
        --admin-insecure-mode 
        --admin 0.0.0.0 7080 
        -e http://${ip_address}:7000/ 
        -l MSP1-Agent
    depends_on:
      - msp1-tails-server
    # volumes:
      # - ${dir_name}/pool_transactions_genesis:/var/lib/indy/my-net/pool_transactions_genesis
      # - ${dir_name}/.indy_client_hr:/home/indy/.indy_client

  msp2-server:
    container_name: msp2-server
    build:
      context: .
      dockerfile: ./Dockerfile.run
    ports:
      - 9229:9229
    command: >
      node MSP_server.js
        --ip ${ip_address}
        --port 9229
        --name MSP2
        --agentUrl http://${ip_address}:8050
        --schemaName MSP2-Ticket
    depends_on:
      - msp2-agent

  msp2-tails-server:
    container_name: msp2-tails-server
    build:
      context: ./indy-tails-server
      dockerfile: ./docker/Dockerfile.tails-server
    ports:
      - 6544:6544
    command: >
      tails-server
        --host 0.0.0.0
        --port 6544
        --log-level debug
        --storage-path /home/indy/tails
    # volumes:
    #  - ${dir_name}/.indy_tails:/home/indy/tails

  msp2-agent:
    container_name: msp2-agent
    build:
      context: ./aries-cloudagent-python
      dockerfile: ./docker/Dockerfile.run
    ports:
      - 10000:10000
      - 8050:8050
    entrypoint: aca-py
    command: >
      start
        --auto-provision
        --tails-server-base-url http://${ip_address}:6544
        --webhook-url http://${ip_address}:9229
        --auto-respond-credential-proposal
        --auto-respond-credential-offer
        --auto-respond-credential-request
        --auto-verify-presentation
        --inbound-transport http 0.0.0.0 10000
        --inbound-transport ws 0.0.0.0 10001
        --outbound-transport ws
        --outbound-transport http
        --genesis-url http://${ip_address}:9000/genesis
        --log-level info
        --seed 000000000000000000000000Steward2
        --wallet-type indy
        --wallet-key StewardWallet2
        --wallet-name StewardWallet2
        --admin-insecure-mode
        --admin 0.0.0.0 8050
        -e http://${ip_address}:10000/
        -l MSP2-Agent
    # volumes:
      # - ${dir_name}/pool_transactions_genesis:/var/lib/indy/my-net/pool_transactions_genesis
      # - ${dir_name}/.indy_client_hr:/home/indy/.indy_client

  verifier-agent:
    container_name: verifier-agent
    build:
      context: ./aries-cloudagent-python
      dockerfile: ./docker/Dockerfile.run
    ports:
      - 12000:12000
      - 12080:12080
    entrypoint: aca-py
    command: >
      start
        --auto-provision
        --webhook http://${ip_address}:8001/intranet
        --auto-respond-credential-proposal 
        --auto-respond-credential-offer 
        --auto-respond-credential-request
        --auto-verify-presentation 
        --inbound-transport http 0.0.0.0 9000 
        --inbound-transport ws 0.0.0.0 9001 
        --outbound-transport ws 
        --outbound-transport http
        --genesis-url http://${ip_address}:9000/genesis
        --log-level info
        --seed 000000000000000000000000Verifier
        --wallet-type indy
        --wallet-local-did
        --wallet-key VerifierWallet
        --wallet-name VerifierWallet
        --admin-insecure-mode 
        --admin 0.0.0.0 9080 
        -e http://${ip_address}:9000/ 
        -l Verifier-Agent
    # volumes:
      # - ${dir_name}/pool_transactions_genesis:/var/lib/indy/my-net/pool_transactions_genesis
      # - ${dir_name}/.indy_client_intranet:/home/indy/.indy_client
